registry:
  images:
    api: ghcr.io/krateoplatformops/api:latest

log:
  level: "info"

api:
  baseUrl: https://api.krateo.site/
  cookie:
    secret: "krateo-site"
    httpOnly: "true"
    signed: "true"
    name: "krateo-platformops"
    maxAge: "604800" # 7 days
    secure: "true"
    domain: "krateo.site"
    sameSite: "Strict"
  uris:
    datastore: "http://datastore-svc.krateo-dev.svc"
    deployment: "http://deployment-svc.krateo-dev.svc"
    template: "http://template-svc.krateo-dev.svc"
    endpoint: "http://endpoint-svc.krateo-dev.svc"
    app: "https://krateo.site"
